/* Chương II · Chữ Là Luật 字即法 — vocabulary and the 14 maps (8 Nhập môn + 6 Cao thủ). */
/* ================= Chương II: Chữ Là Luật (rules-as-words puzzle) ================= */
const C2K = {
  mouse: { han: '𤝞', vi: 'CHUỘT' }, cat: { han: '貓', vi: 'MÈO' }, wall: { han: '墻', vi: 'TƯỜNG' }, water: { han: '渃', vi: 'NƯỚC' },
  fire: { han: '焒', vi: 'LỬA' }, fish: { han: '𩵜', vi: 'CÁ' }, gate: { han: '𨶛', vi: 'CỔNG' }, hay: { han: '稴', vi: 'RƠM' }, jar: { han: '𡑓', vi: 'CHUM' },
  key: { han: '匙', vi: 'CHÌA' }, door: { han: '𨷯', vi: 'CỬA' }, rock: { han: '坧', vi: 'ĐÁ' }, cloud: { han: '𩄲', vi: 'MÂY' }, text: { han: '𡨸', vi: 'CHỮ' },
};
const C2P = { you: { han: '𠫾', vi: 'ĐI' }, push: { han: '𢩽', vi: 'ĐẨY' }, stop: { han: '振', vi: 'CHẶN' }, sink: { han: '沈', vi: 'CHÌM' }, hot: { han: '燶', vi: 'NÓNG' }, win: { han: '勝', vi: 'THẮNG' },
  open: { han: '𢲫', vi: 'MỞ' }, shut: { han: '鎖', vi: 'KHOÁ' }, float: { han: '𢒎', vi: 'BAY' }, pull: { han: '捁', vi: 'KÉO' }, move: { han: '𧼋', vi: 'CHẠY' }, weak: { han: '夭', vi: 'YẾU' } };
// the little words between: LÀ, VÀ, KHÔNG, CÓ
const C2OPS = { is: { han: '羅', vi: 'LÀ' }, and: { han: '吧', vi: 'VÀ' }, not: { han: '空', vi: 'KHÔNG' }, has: { han: '固', vi: 'CÓ' } };
const C2THING = { m: 'mouse', c: 'cat', w: 'wall', '~': 'water', f: 'fire', s: 'fish', g: 'gate', h: 'hay', j: 'jar', k: 'key', d: 'door', r: 'rock', o: 'cloud' };
const C2NOUN = { M: 'mouse', C: 'cat', W: 'wall', N: 'water', F: 'fire', S: 'fish', G: 'gate', H: 'hay', J: 'jar', K: 'key', D: 'door', R: 'rock', O: 'cloud', T: 'text' };
const C2PROP = { 1: 'you', 2: 'push', 3: 'stop', 4: 'sink', 5: 'hot', 6: 'win', 7: 'open', 8: 'shut', 9: 'float', '<': 'pull', '^': 'move', '!': 'weak' };
const C2OP = { '=': 'is', '&': 'and', '-': 'not', '+': 'has' };

/* map legend: lowercase = objects (k chìa, d cửa, r đá, o mây too), UPPERCASE = noun words (T = CHỮ), = LÀ, & VÀ, - KHÔNG, + CÓ,
   1..9 = ĐI ĐẨY CHẶN CHÌM NÓNG THẮNG MỞ KHOÁ BAY, < KÉO, ^ CHẠY, ! YẾU. dirs: [[x, y, 'L']] faces a thing (CHẠY). */
const C2LEVELS = [
  {
    han: '尋𨶛', name: 'Tìm cổng', paper: 'yellow', key: 0,
    hint: "CHUỘT LÀ ĐI nên chuột đi được, nhưng cổng chưa phải đích vì ba chữ CỔNG, LÀ, THẮNG còn nằm rải rác. Đẩy chúng thành một hàng để ghép CỔNG LÀ THẮNG, rồi đưa chuột tới cổng.",
    map: ["..........",".W=3ww..w.",".w..w..w..","..wM=1.w..",".w..w...w.",".m.wG.6=g.",".........."],
    fixed: [],
  },
  {
    han: '扱𡨸', name: 'Ghép chữ', paper: 'pink', key: 2,
    hint: "Lần này TƯỜNG LÀ CHẶN chắn lối tới các chữ. Phá câu đó trước rồi mới ghép được CỔNG LÀ THẮNG. Tính trước đường đẩy: đẩy nhầm một chữ vào góc là phải hoàn tác (Z).",
    map: ["..........",".W=3G...g.","..w.wwww..",".w.wM=1.w.",".w.w.ww.m.","...ww.w6=.",".........."],
    fixed: [],
  },
  {
    han: '破律', name: 'Phá luật', paper: 'blue', key: -3,
    hint: "Cổng bị tường vây kín vì TƯỜNG LÀ CHẶN. Tách một chữ ra khỏi câu đó thì tường thành vật đi xuyên qua được, nhưng câu luật nằm ở chỗ khó với tới.",
    map: ["..........",".w...=www.","..wG..wgw.","..wM..www.",".m.=.W=36.","..w1.www..",".........."],
    fixed: [],
  },
  {
    han: '些羅勝', name: 'Ta là thắng', paper: 'white', key: 0,
    hint: "Cổng bị vây bởi tường không phá được (chữ có đinh ghim ở góc). Đổi đích: nếu ghép được CHUỘT LÀ THẮNG thì chính con chuột là đích.",
    map: ["..........","....m.www.",".6....wgw.",".w.M.wwww.","..M=1..w..",".=G.....=.","W=3......."],
    fixed: [[0,6],[1,6],[2,6]],
  },
  {
    han: '變形', name: 'Biến hình', paper: 'sage', key: -2,
    hint: "Mèo rất nóng, chạm vào là chết (MÈO LÀ NÓNG). Nếu ghép được MÈO LÀ CÁ thì mèo hoá cá, đi qua thoải mái.",
    map: ["...=.w....","m.C.Gw....","M=1.ww....","w.S=.c...g","w...6w....",".....w....","C=5..wW=3."],
    fixed: [[0,6],[1,6],[2,6],[6,6],[7,6],[8,6]],
  },
  {
    han: '沈', name: 'Chìm', paper: 'lilac', key: -1,
    hint: "Nước là CHÌM: thứ gì rơi xuống nước thì cả hai cùng biến mất. Chum chỉ đẩy được khi có luật CHUM LÀ ĐẨY.",
    map: ["w=ww6~....","wwJMm~....","ww2==~..g.","w..1.~....","w..wG~....","jw.w.~....",".....~N=4."],
    fixed: [[6,6],[7,6],[8,6]],
  },
  {
    han: '火門', name: 'Lửa thành cổng', paper: 'pink', key: 2,
    hint: "Lửa cháy rực chắn đường (LỬA LÀ NÓNG). Nếu ghép được LỬA LÀ CỔNG thì mọi ngọn lửa hoá thành cổng, chạm vào là thắng.",
    map: ["Gw...f....","ww..mf....","=F...f..g.",".w..Mf....","6www=f....",".=..1f....",".....fF=5."],
    fixed: [[6,6],[7,6],[8,6]],
  },
  {
    han: '全圖', name: 'Trọn bức tranh', paper: 'yellow', key: 0,
    hint: "Bức cuối phần Nhập môn: chìm nước và biến hình, cùng với nghệ thuật đẩy chữ.",
    map: [".G.~wwww...","=S.~jw.w...",".=J~M=1w...","...~C.wc..g","w..~m=.w...","w..~2.6w...","N=4~C=5wW=3"],
    fixed: [[0,6],[1,6],[2,6],[4,6],[5,6],[6,6],[8,6],[9,6],[10,6]],
  },
  {
    han: "推牆", name: "Tường đẩy được", paper: "sage", key: -2, hard: true,
    riddle: "Tường chặn thì đã sao? Thứ gì chặn đường cũng có lúc phải nhường.",
    hint: "Ghép dọc TƯỜNG / LÀ / ĐẨY ngay dưới chữ TƯỜNG cố định. Tường vẫn chặn, nhưng đẩy được, nên xô tường ra khỏi cổng.",
    map: ["M=1.....W=3",".........w.",".=..w.2....",".w...wwwwww","w..w.wwgwww",".m.wwwwwwww",".......G=6."],
    fixed: [[0,0],[1,0],[2,0],[8,0],[9,0],[10,0],[7,6],[8,6],[9,6]],
  },
  {
    han: "借還", name: "Mượn tạm", paper: "pink", key: 2, hard: true,
    riddle: "Cổng bị tường vây kín. Có mượn thì phải có trả.",
    hint: "Mượn chữ CỔNG và LÀ để ghép dọc TƯỜNG LÀ CỔNG: mọi bức tường hoá thành cổng, và vẫn là cổng dù luật mất. Rồi trả hai chữ về để ghép lại CỔNG LÀ THẮNG.",
    map: ["ww.W=3ww","ww...m.w","w.G..w.w","w6.=..ww","w...w..w","wM=1.wgw","wwwwwwww"],
    fixed: [[3,0],[4,0],[5,0],[1,5],[2,5],[3,5]],
  },
  {
    han: "水火", name: "Nước dập lửa", paper: "blue", key: -3, hard: true,
    riddle: "Nước lấy đâu mà dập lửa? Nước ở ngay đó thôi, chỉ là chưa chịu đi.",
    hint: "Ghép dọc NƯỚC / LÀ / ĐẨY dưới chữ NƯỚC cố định, rồi đẩy một ô nước vào ô lửa. Thứ gì rơi vào chỗ CHÌM cũng biến mất cùng nó.",
    map: ["N=4...~f..","w...2w~f..",".m.www~f.g","...w=.~f..",".w...w~f..","F=5M=1~f..","G=6...~f.."],
    fixed: [[0,0],[1,0],[2,0],[0,5],[1,5],[2,5],[3,5],[4,5],[5,5],[0,6],[1,6],[2,6]],
  },
  {
    han: "自焚", name: "Lửa tự thiêu", paper: "white", key: 0, hard: true,
    riddle: "Lửa nóng đến mức đốt cả chính mình, nếu nó chịu làm chủ.",
    hint: "Ghép dọc LỬA / LÀ / ĐI ngay trên chữ ĐI cố định. Lửa vừa là mình vừa NÓNG nên tự thiêu rụi. (Ghép LỬA LÀ CHUỘT cũng là một cách.)",
    map: ["...w..f...","w.F...f...","..w...f.g.","m..=w.f...","..w...f...","M=1F=5f...","G=6W=3fwww"],
    fixed: [[0,5],[1,5],[2,5],[3,5],[4,5],[5,5],[0,6],[1,6],[2,6],[3,6],[4,6],[5,6]],
  },
  {
    han: "渡河", name: "Qua sông", paper: "lilac", key: -1, hard: true,
    riddle: "Qua sông phải bỏ lại một thứ, mà thứ nào cũng đang cần.",
    hint: "Dựng CỔNG LÀ THẮNG theo chiều dọc, dùng chung chữ LÀ của CHUỘT LÀ ĐI. Chữ LÀ dư ra đem thả xuống sông: chữ cũng chìm được.",
    map: ["......~.",".w....~.",".M=1..~g",".w....~.","...G..~.",".m.=6.~.","W=3...~.","N=4...~."],
    fixed: [[0,6],[1,6],[2,6],[0,7],[1,7],[2,7],[1,2],[2,2],[3,2]],
  },
  {
    han: "雙身", name: "Hai thân", paper: "yellow", key: 0, hard: true,
    riddle: "Chuột bị nhốt trong hộp, nhưng con cá ngoài kia thì tự do.",
    hint: "Xếp CÁ LÀ ĐI trong chiếc hộp chật để con cá ngoài kia cũng thành mình. Chữ vào góc là không kéo ra được nữa, nên tính trước từng nước đẩy.",
    map: ["wwwwwww.....","w.ww..w..s..","w.1S.mw.....","w.=w..w.w.w.","w.....w.wgw.","wwwwwww.www.","M=1...W=3G=6"],
    fixed: [[0,6],[1,6],[2,6],[6,6],[7,6],[8,6],[9,6],[10,6],[11,6]],
  },
  /* ---- Biến hoá (owner: more words, after Baba Is You); every map checked by tools/c2-solve.js ---- */
  {
    han: "開門", name: "Chìa mở cửa", paper: "yellow", key: 0, bh: true,
    hint: "CỬA LÀ KHOÁ: cửa chặn mọi thứ, trừ thứ MỞ. Ghép CHÌA LÀ MỞ rồi đẩy chìa vào cửa: chìa và cửa cùng mất.",
    map: ["M=1.....W=3.", "K=2.....D=8.", "G=6.........", ".K=....wwwww", ".....7.w...w", ".mk....d.g.w", ".......wwwww"],
    fixed: [[0, 0], [1, 0], [2, 0], [8, 0], [9, 0], [10, 0], [0, 1], [1, 1], [2, 1], [8, 1], [9, 1], [10, 1], [0, 2], [1, 2], [2, 2]],
  },
  {
    han: "破缸", name: "Vò vỡ", paper: "pink", key: 2, bh: true,
    hint: "CHUM CÓ CHÌA: chum mất đi thì để lại chìa. Đổi CHUM LÀ CHẶN thành CHUM LÀ YẾU, rồi bước vào chum cho vỡ.",
    map: ["M=1...W=3...", "G=6...D=8...", "K=7&2.J+K...", "............", "J=3....wwwww", "..!....w...w", ".m..j..d.g.w", ".......wwwww"],
    fixed: [[0, 0], [1, 0], [2, 0], [6, 0], [7, 0], [8, 0], [0, 1], [1, 1], [2, 1], [6, 1], [7, 1], [8, 1], [0, 2], [1, 2], [2, 2], [3, 2], [4, 2], [6, 2], [7, 2], [8, 2]],
  },
  {
    han: "拉石", name: "Kéo đá", paper: "blue", key: -3, bh: true,
    hint: "Đá CHẶN nên không đẩy được. Ghép thêm ĐÁ LÀ KÉO: đứng sát đá rồi bước đi, đá lẽo đẽo theo sau, ngõ sẽ trống.",
    map: ["M=1....G=6", "W=3...R=3.", "..........", ".R..=..www", ".m..<..rrg", ".......www"],
    fixed: [[0, 0], [1, 0], [2, 0], [7, 0], [8, 0], [9, 0], [0, 1], [1, 1], [2, 1], [6, 1], [7, 1], [8, 1]],
  },
  {
    han: "拉字", name: "Chữ kéo", paper: "white", key: 0, bh: true,
    hint: "Chữ nằm trong góc thì không đẩy ra được. Nhưng CHỮ LÀ KÉO: đứng cạnh chữ rồi bước ra xa là chữ đi theo.",
    map: ["G.......6", ".........", ".........", ".....g...", ".........", ".m.......", "=..T=<M=1"],
    fixed: [[3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6]],
  },
  {
    han: "不止", name: "Không chặn", paper: "sage", key: -2, bh: true,
    hint: "TƯỜNG LÀ CHẶN bị ghim cứng. Xếp dọc TƯỜNG / KHÔNG ngay trên chữ CHẶN ấy: TƯỜNG KHÔNG CHẶN thắng luật cũ.",
    map: ["G=6.......", ".....W....", "M......www", "=......wgw", "1.m....www", "....-.....", "...W=3...."],
    fixed: [[0, 0], [1, 0], [2, 0], [0, 2], [0, 3], [0, 4], [3, 6], [4, 6], [5, 6]],
  },
  {
    han: "貓推", name: "Mèo đẩy chữ", paper: "lilac", key: -1, bh: true,
    hint: "Chữ THẮNG nằm trong hộp của mèo, chuột không vào được. Ghép MÈO LÀ CHẠY: mèo tự đi và đẩy chữ hộ.",
    map: ["M=1...W=3..", ".........g.", "C........G.", ".=.wwwwww=w", "...wc.6...w", ".^.wwwwwwww", ".m........."],
    fixed: [[0, 0], [1, 0], [2, 0], [6, 0], [7, 0], [8, 0], [9, 2], [9, 3]],
  },
  {
    han: "有門", name: "Lửa có cổng", paper: "pink", key: 2, bh: true,
    hint: "Chẳng có cổng nào, nhưng LỬA CÓ CỔNG: lửa mất đi thì hiện ra cổng. Ghép LỬA LÀ YẾU rồi đẩy chum vào lửa.",
    map: ["M=1..F+G..", "G=6..F=5..", "..........", "J=2....fff", ".m.j...f.f", "....!..fff", "F=........"],
    fixed: [[0, 0], [1, 0], [2, 0], [5, 0], [6, 0], [7, 0], [0, 1], [1, 1], [2, 1], [5, 1], [6, 1], [7, 1], [0, 3], [1, 3], [2, 3]],
  },
  {
    han: "生鑰", name: "Chìa đẻ chìa", paper: "yellow", key: 0, bh: true,
    hint: "Ba lớp cửa mà chỉ một chìa. Ghép CHÌA CÓ CHÌA trước đã: mỗi lần chìa mở một cửa lại để lại một chìa mới.",
    map: ["M=1...W=3....", "G=6...D=8....", "K=7&2........", "wwwwwwwwwwwww", "..k..d.d.d.g.", "..wwwwwwwwwww", ".m..K......K.", ".......+.....", "............."],
    fixed: [[0, 0], [1, 0], [2, 0], [6, 0], [7, 0], [8, 0], [0, 1], [1, 1], [2, 1], [6, 1], [7, 1], [8, 1], [0, 2], [1, 2], [2, 2], [3, 2], [4, 2]],
  },
  {
    han: "飛河", name: "Bay qua sông", paper: "blue", key: -3, bh: true,
    hint: "CHUỘT LÀ BAY thì qua được sông, nhưng thứ BAY chỉ chạm được thứ cũng BAY: cổng cũng phải bay. Ghép CHUỘT VÀ CỔNG LÀ BAY.",
    map: ["M=1...~~~~....", "N=4...~~~~....", "G=6...~~~~..g.", "..9...~~~~....", ".m.=..~~~~....", "M&..G.~~~~....", "......~~~~...."],
    fixed: [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1], [0, 2], [1, 2], [2, 2], [0, 5], [1, 5]],
  },
  {
    han: "石橋", name: "Bắc cầu đá", paper: "sage", key: -2, bh: true,
    hint: "Bay qua sông, kéo đá theo sau: đá không bay nên rơi xuống sông, đá với nước cùng mất thành chỗ đặt chân. Lấp đủ hai ô rồi bỏ chữ BAY để vào cổng.",
    map: ["M=1...~~...", "N=4...~~...", "R=<...~~.g.", "R=3...~~...", "rr.m..~~G=6", "M=..9.~~...", "......~~..."],
    fixed: [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1], [0, 2], [1, 2], [2, 2], [0, 3], [1, 3], [2, 3], [8, 4], [9, 4], [10, 4], [0, 5], [1, 5]],
  },
  {
    han: "字行", name: "Chữ là mình", paper: "white", key: 0, bh: true,
    hint: "CHỮ LÀ ĐI: mọi chữ cùng đi theo phím. Cho mây chặn bớt vài chữ để xếp CỔNG LÀ THẮNG, nhưng giữ câu CHỮ LÀ ĐI liền một hàng, rồi cho một chữ chạm vào cổng.",
    map: ["ooooooooooo", "o.........o", "oGT=1oo6.=o", "o..o......o", "o.........o", "o..o.g..o.o", "o.........o", "ooooooooooo", "O=3........"],
    fixed: [[0, 8], [1, 8], [2, 8]],
  },
  {
    han: "𤝞羅𤝞", name: "Chuột là chuột", paper: "lilac", key: -1, bh: true,
    hint: "Đẩy chữ CHUỘT qua ngõ hẹp là tự ghép thành CHUỘT LÀ MÈO. Ghép trước CHUỘT LÀ CHUỘT: chuột giữ nguyên là chuột, không hoá thành gì khác.",
    map: ["W=3.G=6....", "M=1...=....", "..M.m...M..", "wwwwww.wwww", ".....wMw...", ".....w.w...", "..g.......w", ".......=C.w"],
    fixed: [[0, 0], [1, 0], [2, 0], [4, 0], [5, 0], [6, 0], [0, 1], [1, 1], [2, 1], [7, 7], [8, 7]],
  },
  /* ---- Siêu khó (30 maps, open after the last Biến hoá map); every map checked by tools/c2-solve.js and tools/c2-chain.js ---- */
  {
    han: "授權", name: "Trao quyền", paper: "sage", key: -2, sk: true,
    riddle: "Con cá đi được mà chẳng tới được cổng; con chuột ở cạnh cổng mà chẳng nhúc nhích được.",
    hint: "CÁ LÀ ĐI: con cá làm việc trước. Ghép CỔNG LÀ THẮNG cho xong rồi mới đẩy chữ LÀ của CÁ LÀ ĐI sang khe giữa CHUỘT và ĐI: quyền đi trao sang chuột. Trao sớm quá thì cá đứng im mà chuột chưa có đích.",
    map: [".SMw......", "s=........", ".11..wwwww", "..w..w...w", ".=...w.g.w", ".G6..w.m.w", "W=3..wwwww"],
    fixed: [[2, 0], [2, 2], [0, 6], [1, 6], [2, 6]],
  },
  {
    han: "過橋", name: "Qua cầu rút ván", paper: "blue", key: -3, sk: true,
    riddle: "Sông rộng hai ô mà chỉ có một cái chum.",
    hint: "Chum đang nằm đúng chỗ chữ ĐẨY phải vào. Ghép CHUM LÀ ĐẨY, đẩy chum xuống ô sông thứ nhất. Chum chìm rồi thì luật ấy hết việc: rút chữ ĐẨY ra, đẩy qua chỗ vừa lấp xuống ô sông thứ hai.",
    map: ["M=1.m~~...", ".....~~.g.", "J=j..~~...", ".....~~...", ".....~~...", "..2..~~G=6", "N=4..~~..."],
    fixed: [[0, 0], [1, 0], [2, 0], [0, 2], [1, 2], [0, 6], [1, 6], [2, 6], [7, 5], [8, 5], [9, 5]],
  },
  {
    han: "轉生", name: "Hoá kiếp", paper: "yellow", key: 0, sk: true,
    riddle: "Rơm muốn thành cổng thì phải đi qua một kiếp cá.",
    hint: "Chẳng có cổng nào, mà CÁ LÀ CỔNG thì chẳng có cá. Chữ LÀ rời duy nhất nằm trong TƯỜNG LÀ CHẶN: rút nó ra rồi đặt vào giữa RƠM và CÁ ở hàng trên cùng, thành RƠM LÀ CÁ LÀ CỔNG: rơm hoá cá, cá hoá cổng.",
    map: ["....wH.S=G", "........m=", "......M=16", ".w.w.w....", "..w.W..h..", "....=.....", "....3....."],
    fixed: [[7, 0], [8, 0], [9, 0], [9, 1], [9, 2], [6, 2], [7, 2], [8, 2], [4, 4], [4, 6]],
  },
  {
    han: "牆水", name: "Tường hoá nước", paper: "lilac", key: -1, sk: true,
    riddle: "Cổng nằm sau bức tường dày, mà đá thì chẳng phá nổi tường.",
    hint: "Ghép ĐÁ LÀ ĐẨY, rồi dựng dọc TƯỜNG / LÀ / NƯỚC dưới chữ TƯỜNG: mọi bức tường hoá nước, mà NƯỚC LÀ CHÌM. Đẩy hai hòn đá xuống lấp lối vào cổng. Tường lẻ giữa sân cũng hoá nước, đừng phí đá.",
    map: ["W=3.R.www", "..=.=mwww", "..r.r.www", "w.N.2.wwg", ".w....www", "M=1N=4G=6"],
    fixed: [[0, 0], [1, 0], [2, 0], [4, 0], [4, 1], [0, 5], [1, 5], [2, 5], [3, 5], [4, 5], [5, 5], [6, 5], [7, 5], [8, 5]],
  },
  {
    han: "一字", name: "Một chữ ba việc", paper: "pink", key: 2, sk: true,
    riddle: "Một chữ LÀ mà phải gánh ba việc, xong việc này mới sang việc khác.",
    hint: "Chum bị nhốt trong buồng tường, và chữ LÀ duy nhất đang nằm trong TƯỜNG LÀ CHẶN. Rút nó ra cho tường hết chặn, đem ghép CHUM LÀ ĐẨY để lùa chum ra sông, rồi chở chữ LÀ qua chỗ vừa lấp để ghép CỔNG LÀ THẮNG.",
    map: ["wwwww..m~M=1", "wj..w...~..g", "w...W...~...", "w...=...~...", "w...3...~...", "wwwwwJ.2~G.6", "N=4.....~..."],
    fixed: [[9, 0], [10, 0], [11, 0], [4, 2], [4, 4], [0, 6], [1, 6], [2, 6], [5, 5], [7, 5], [9, 5], [11, 5]],
  },
  {
    han: "替命", name: "Thế mạng", paper: "white", key: 0, sk: true,
    riddle: "Sông rộng hai hàng, và con mèo cũng muốn góp một tay.",
    hint: "Ghép MÈO LÀ ĐI: mèo bước theo chuột từng bước. Lùa mèo nhảy xuống hàng nước thứ nhất mà chuột không sẩy chân, rồi rút chữ LÀ của MÈO LÀ ĐI, đẩy qua chỗ vừa lấp xuống hàng nước thứ hai.",
    map: ["M=1.m~~...", ".C...~~.g.", "..c..~~...", ".1...~~...", ".....~~...", "..=..~~G=6", "N=4..~~..."],
    fixed: [[0, 0], [1, 0], [2, 0], [1, 1], [1, 3], [0, 6], [1, 6], [2, 6], [7, 5], [8, 5], [9, 5]],
  },
  {
    han: "池鼠", name: "Ao chuột", paper: "sage", key: -2, sk: true,
    riddle: "Trong vườn kín có cái ao, mà vườn thì chẳng ai vào được.",
    hint: "Ghép dọc NƯỚC / LÀ / CHUỘT: nước trong ao hoá thành chuột và cùng đi theo phím với con chuột ngoài vườn. Mấy con chuột trong vườn phải cùng nhau xếp CỔNG LÀ THẮNG; con nào chạm cổng là thắng.",
    map: ["W=3.wwwwwww", "....ww.ww.w", "..N.ww..=~w", "=...w.G..~w", "M=1.w6...gw", ".m..w.w..ww", "....wwwwwww"],
    fixed: [[0, 0], [1, 0], [2, 0], [0, 3], [0, 4], [1, 4], [2, 4]],
  },
  {
    han: "熱門", name: "Cổng bỏng", paper: "pink", key: 2, sk: true,
    riddle: "Cổng nóng bỏng tay: chạm vào là cháy, mà không chạm thì chẳng thắng.",
    hint: "CỔNG LÀ NÓNG ghim cứng, không phá được. Đổi cổng thành thứ khác: ghép dọc CỔNG / LÀ / RƠM và ngang RƠM LÀ THẮNG, hai câu dùng chung chữ RƠM. Cổng hoá rơm, rơm thì không nóng.",
    map: ["M=1..G=5", ".w...=..", "...==6..", ".wHG.wgm", "...w..w.", "........", "W=3....w"],
    fixed: [[0, 0], [1, 0], [2, 0], [5, 0], [6, 0], [7, 0], [5, 1], [4, 2], [5, 2], [0, 6], [1, 6], [2, 6]],
  },
  {
    han: "十字", name: "Ngã tư", paper: "yellow", key: 0, sk: true,
    riddle: "Một chữ LÀ, hai câu luật, chung một ô.",
    hint: "Cổng nằm trong hốc tường sát mép, chỉ vào được khi tường đẩy được. Đặt chữ LÀ vào ô giữa TƯỜNG / ĐẨY (dọc) và CỔNG / THẮNG (ngang): một chữ làm hai luật, rồi xô tường mà vào cổng.",
    map: ["W=3..wgw", ".....6w.", "m.W.....", "wG......", "ww2w..ww", "....w.=.", "M=1....."],
    fixed: [[0, 0], [1, 0], [2, 0], [2, 2], [1, 3], [2, 4], [0, 6], [1, 6], [2, 6]],
  },
  {
    han: "浮沉", name: "Lúc chìm lúc nổi", paper: "blue", key: -3, sk: true,
    riddle: "Nước sâu thì dìm được mèo, nước cạn thì người mới lội qua.",
    hint: "Chỉ một chữ LÀ: lúc làm NƯỚC LÀ CHÌM, lúc làm CỔNG LÀ THẮNG. Dìm con mèo xuống sông khi nước còn chìm, rồi đem chữ LÀ sang ghép CỔNG LÀ THẮNG: nước hết chìm, lội qua ô còn lại tới cổng.",
    map: ["M=1G.N......", ".....=...w..", ".w.6.4...w.m", "....wwwwwwww", "....c..~~.gw", "....wwwwwwww", "W=3C=2......"],
    fixed: [[0, 0], [1, 0], [2, 0], [3, 0], [5, 0], [3, 2], [5, 2], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6]],
  },
  {
    han: "生鼠", name: "Chuột đẻ chuột", paper: "lilac", key: -1, sk: true,
    riddle: "Sông rộng, cửa khoá, mà chuột thì chỉ có một mạng.",
    hint: "Ghép dọc CHUỘT / CÓ / CHUỘT dưới chữ CHUỘT cố định: chuột mất đi thì một con chuột khác hiện ra ngay chỗ đó. Thế là cứ lội xuống sông, mỗi bước chìm mất một ô nước. Ghép thêm CHUỘT LÀ ĐI VÀ MỞ để chính chuột mở cửa.",
    map: ["M=1&..~~~.ww", ".....w~~~.dg", ".+..M.~~~.ww", ".m..7.~~~...", "w.....~~~...", "N=4D=8G=6W=3"],
    fixed: [[0, 0], [1, 0], [2, 0], [3, 0], [0, 5], [1, 5], [2, 5], [3, 5], [4, 5], [5, 5], [6, 5], [7, 5], [8, 5], [9, 5], [10, 5], [11, 5]],
  },
  {
    han: "字鑰", name: "Chữ làm chìa", paper: "yellow", key: 0, sk: true,
    riddle: "Không có chìa nào, nhưng chữ thì thừa ra một chữ.",
    hint: "Đặt chữ LÀ giữa CHỮ và MỞ: mọi chữ thành chìa. Đẩy chữ VÀ (chữ thừa) vào cửa, chữ và cửa cùng mất. Rồi lấy lại chữ LÀ để ghép CỔNG LÀ THẮNG.",
    map: [".T....wwg", "......wwd", ".7..G.6..", "..&..=...", ".m.......", "wwwwwwwww", "M=1D=8W=3"],
    fixed: [[1, 0], [1, 2], [4, 2], [6, 2], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6]],
  },
  {
    han: "拉推", name: "Kéo rồi đẩy", paper: "blue", key: -3, sk: true,
    riddle: "Chìa nằm tận đáy ngách hẹp, đẩy vào thì chỉ kẹt thêm.",
    hint: "Ghép CHÌA LÀ KÉO, vào ngách đứng ngay dưới chìa rồi lùi ra: chìa lẽo đẽo theo sau. Ra tới ngoài thì đẩy chữ ĐẨY vào chỗ chữ KÉO, rồi đẩy chìa vào cửa.",
    map: ["...G=6wkww", "K=....w.ww", "=.....w.wg", "7.<.2....d", ".m........", "wwwwwwwwww", "M=1D=8W=3."],
    fixed: [[3, 0], [4, 0], [5, 0], [0, 1], [1, 1], [0, 2], [0, 3], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6]],
  },
  {
    han: "套缸", name: "Lồng trong lồng", paper: "sage", key: -2, sk: true,
    riddle: "Hòn đá giấu cái chum, cái chum giấu chiếc chìa.",
    hint: "ĐÁ CÓ CHUM, CHUM CÓ CHÌA. Ghép CHUM LÀ ĐẨY và ĐÁ LÀ YẾU: bước vào đá cho vỡ ra chum, đẩy chum xuống sông cho chìm ra chìa. Rồi dời chữ ĐẨY sang CHÌA mà đẩy chìa vào cửa.",
    map: ["wwww.w~wwG=6", "R=....~wwwww", "+...r.~wwwww", "J=..!.~wwwww", "+.....~...dg", "K=....~wwwww", "=..m2.~wwwww", "7w...w~wwwww", "M=1N=4D=8W=3"],
    fixed: [[9, 0], [10, 0], [11, 0], [0, 1], [1, 1], [0, 2], [0, 3], [1, 3], [0, 4], [0, 5], [1, 5], [0, 6], [0, 7], [0, 8], [1, 8], [2, 8], [3, 8], [4, 8], [5, 8], [6, 8], [7, 8], [8, 8], [9, 8], [10, 8], [11, 8]],
  },
  {
    han: "助跑", name: "Chạy đà", paper: "pink", key: 2, sk: true,
    riddle: "Sông chỉ rộng một bước, mà chuột thì không biết bơi.",
    hint: "Ghép CHUỘT LÀ CHẠY: mỗi lần bấm chuột đi hai ô, nhảy vọt qua một ô nước. Bên kia sông, đẩy chữ cũng hai ô một lần; đâm vào vật chặn thì chuột lùi lại một ô. Ghép CỔNG LÀ THẮNG rồi tính cho đúng bước dừng trên cổng.",
    map: ["M=1w.~......", "N=4w.~ww.6.w", "W=3w.~=G..w.", "M=.w.~......", ".m^..w...w..", ".....w.www.g"],
    fixed: [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1], [0, 2], [1, 2], [2, 2], [0, 3], [1, 3]],
  },
  {
    han: "石渠", name: "Đá đào sông", paper: "white", key: 0, sk: true,
    riddle: "Một hòn đá mà lấp được cả dòng sông.",
    hint: "Ghép NƯỚC CÓ ĐÁ: đá rơi xuống nước thì ô nước mất mà đá lại hiện ra, cứ thế đẩy đá xuyên qua sông. Rồi mang chữ CÓ qua bờ bên kia, ghép CHUM CÓ CỔNG và đẩy chum xuống sông.",
    map: ["..N...~~~J.G", "......~~~...", "..R...~~~...", ".m..r.~~~...", "...+..~~~.j.", "M=1...~~~J=2", "R=2N=4~~~G=6"],
    fixed: [[2, 0], [2, 2], [9, 0], [11, 0], [0, 5], [1, 5], [2, 5], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [9, 5], [10, 5], [11, 5], [9, 6], [10, 6], [11, 6]],
  },
  {
    han: "雙行", name: "Đi đôi", paper: "yellow", key: 0, sk: true,
    riddle: "Cửa ở bên kia bức vách, chìa cũng ở bên kia.",
    hint: "Ghép CHÌA VÀ CHUỘT LÀ ĐI: chìa bước theo từng bước của chuột, mỗi bên một mê cung. Dẫn chìa vào cửa, rồi chuột qua cửa mà vào cổng.",
    map: ["K=7G=6www...", ".ww.www...&w", "..k.wwgww..m", "..ww..d.....", "w...w.w..w..", "......w.K...", "W=3D=8w..M=1"],
    fixed: [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [9, 6], [10, 6], [11, 6]],
  },
  {
    han: "貓魚", name: "Mèo hoá cá", paper: "pink", key: 2, sk: true,
    riddle: "Cổng nằm trong phòng của con mèo chạy, mà chuột không vào được.",
    hint: "Ghép MÈO CÓ CÁ trước, rồi mới ghép MÈO LÀ YẾU: mèo đang chạy chạm phải thứ gì là vỡ, để lại một con cá. CÁ LÀ ĐI nên cá đi thay chuột tới cổng. Ghép YẾU trước thì mèo mất trắng.",
    map: ["w.....wwwwww", "C=....w.g.ww", "...m.ww.h.cw", "S=1.w.wwwwww", "w.!.......+.", "....ww..w...", "M=1W=3G=6C=^"],
    fixed: [[0, 1], [1, 1], [0, 3], [1, 3], [2, 3], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6], [9, 6], [10, 6], [11, 6]],
  },
  {
    han: "牽戶", name: "Dắt cửa", paper: "blue", key: -3, sk: true,
    riddle: "Hai cánh cửa chặn ngõ cụt, mà chỉ có một chữ LÀ cho hai việc.",
    hint: "Đặt chữ LÀ giữa CỬA và KÉO: đứng sát cửa rồi bước đi, cả hai cánh cửa nối đuôi theo sau. Dắt cửa ra khỏi ngõ, vòng ra phía sau chúng, rồi đem chữ LÀ ghép CỔNG LÀ THẮNG.",
    map: ["gdd.......w.", "www.w.......", "ww.w..w=D..w", "...w.w......", "..w...ww<...", "w..w.w....m.", "M=1D=8W=3G.6"],
    fixed: [[8, 2], [8, 4], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6], [9, 6], [11, 6]],
  },
  {
    han: "字門", name: "Chữ có cổng", paper: "lilac", key: -1, sk: true,
    riddle: "Cả bức tranh không có lấy một cái cổng.",
    hint: "Ghép dọc CHỮ / CÓ ngay trên CỔNG LÀ THẮNG: CHỮ CÓ CỔNG VÀ CỔNG LÀ THẮNG cùng đứng. Chữ nào chìm xuống sông thì để lại một cái cổng. Chữ thừa duy nhất là chữ LÀ của TƯỜNG LÀ CHẶN: rút nó ra cho rào tường hết chặn rồi thả xuống sông.",
    map: ["....r..rr.w~", "r.........w~", "m.r.rW=3..w~", ".......rT.w~", "+......r..w~", "G=6M=1N=4R=3"],
    fixed: [[5, 2], [7, 2], [0, 5], [1, 5], [2, 5], [3, 5], [4, 5], [5, 5], [6, 5], [7, 5], [8, 5], [9, 5], [10, 5], [11, 5]],
  },
  {
    han: "並步", name: "Song hành", paper: "sage", key: -2, sk: true,
    riddle: "Hai đứa cùng nhấc chân một lúc, đứa này vướng thì đứa kia vẫn bước.",
    hint: "CHUỘT VÀ MÈO LÀ ĐI: một phím, cả chuột lẫn mèo cùng đi. Con nào vướng tường thì đứng lại, con kia vẫn bước, nhờ thế mà xê dịch được từng con. Mèo đẩy chữ THẮNG ghép CỔNG LÀ THẮNG và đẩy chữ NÓNG ra khỏi LỬA LÀ NÓNG để chuột qua lửa vào cổng; mèo đi nhầm vào lửa cũng chết.",
    map: ["f...fwG=c.w", "..f.fw..6.w", "..wm.wfF..w", ".fwf.w.=w.w", "fwg.wwf5..w", "wwwwwwwwwww", "W=3M&C=1..."],
    fixed: [[6, 0], [7, 0], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [7, 2], [7, 3]],
  },
  {
    han: "靜立", name: "Đứng yên", paper: "white", key: 0, sk: true,
    riddle: "Muốn một đứa đứng lại thì phải bảo nó, rồi lại phải gọi nó đi tiếp.",
    hint: "Chuột và mèo cùng đi theo một phím (CHUỘT VÀ MÈO LÀ ĐI). Chèn chữ KHÔNG vào giữa MÈO và ĐI: MÈO KHÔNG ĐI thắng luật kia, mèo đứng yên cho chuột đi một mình. Rút KHÔNG ra là mèo lại đi theo. Thay phiên như thế để mèo đẩy THẮNG thành CỔNG LÀ THẮNG.",
    map: [".....wG=..w", ".w...w....w", ".C.www.w..w", "...-mw.6..w", "g1.w.w.w.cw", "wwwwwwwwwww", "W=3M&C=1..."],
    fixed: [[6, 0], [7, 0], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [1, 2], [1, 4]],
  },
  {
    han: "貓跑", name: "Mèo chạy rông", paper: "yellow", key: 2, sk: true,
    riddle: "Con mèo chạy không biết đường dừng, chỉ có người bảo nó mới dừng.",
    hint: "Ghép MÈO LÀ CHẠY thì mèo tự chạy mỗi bước, vướng thì quay đầu, chạy vào chữ là đẩy chữ. Để mèo đẩy THẮNG vào chỗ trống dưới CỔNG LÀ, rồi rút chữ LÀ ra cho mèo dừng ngay, kẻo nó đẩy chữ đi mất.",
    map: ["..w.mw..G.w", ".=...www=.w", "..C..wc6..w", "wg...ww.www", "..^..w.w.ww", "wwwwwwwwwww", "W=3M=1....."],
    fixed: [[8, 0], [8, 1], [2, 2], [2, 4], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6]],
  },
  {
    han: "交手", name: "Trao tay", paper: "pink", key: 2, sk: true,
    riddle: "Không có cổng, đích ở ngay trong tay, nhưng tự mình thì không cầm được.",
    hint: "Chẳng có cổng nào, lúc đầu chỉ mèo đi được. Cho mèo đẩy chữ VÀ vào chỗ trống ở hàng dưới cùng: CHUỘT VÀ MÈO LÀ ĐI, hai con cùng đi. Ghép CHỮ LÀ THẮNG thì mọi chữ là đích, nhưng bước vào chữ là đẩy chữ đi, không đứng chung được: phải đẩy một chữ vào đúng ô của bạn mình. Vào lửa là chết.",
    map: ["T.......", "w.w...w.", ".=...w.m", "w6....w.", "w.wfww..", "....c.&.", "..W=3F=5", "M.C=1..."],
    fixed: [[2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [0, 7], [2, 7], [3, 7], [4, 7]],
  },
  {
    han: "脆門", name: "Cổng giòn", paper: "white", key: 0, sk: true,
    riddle: "Cổng mỏng như vỏ trứng, chạm nhẹ là vỡ, chạm bằng chữ cũng vỡ.",
    hint: "CỔNG LÀ YẾU bị ghim: có gì chung ô là cổng vỡ, chuột bước vào cũng vỡ, chữ đẩy qua cũng vỡ. Chèn KHÔNG vào giữa CỔNG và YẾU ở góc trên: CỔNG KHÔNG YẾU thắng luật kia. Rồi mới đẩy THẮNG ghép CỔNG LÀ THẮNG, và đừng để chữ nào lăn qua cổng trước lúc đó.",
    map: ["..Gw...g.", ".......w.", "..!.wmw..", "..G=.w.6w", ".......-.", ".....w...", "W=3M=1G=!"],
    fixed: [[0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6], [2, 0], [2, 2], [2, 3], [3, 3]],
  },
  {
    han: "保身", name: "Giữ lấy mình", paper: "blue", key: -3, sk: true,
    riddle: "Ô trống ấy nối được hai câu một lúc, một câu cứu mình, một câu hại mình.",
    hint: "Đẩy chữ CỔNG vào ô trống thì cùng lúc ghép CỔNG LÀ THẮNG và CHUỘT LÀ CỔNG: chuột hoá cổng, hết đường đi. Ghép trước CHUỘT LÀ CHUỘT (dọc trên chữ CHUỘT ở góc dưới) thì chuột giữ nguyên là chuột.",
    map: ["gm..M.ww.", "..w.=ww..", "..w=.=6.w", ".G.....w.", "M.w..w...", "..w.w....", "M=1W=3..."],
    fixed: [[4, 0], [4, 1], [5, 2], [6, 2], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6]],
  },
  {
    han: "溺貓", name: "Dìm mèo", paper: "blue", key: -3, sk: true,
    riddle: "Con mèo nóng chạy đi chạy lại không biết mệt, chỉ có nước mới cản được nó.",
    hint: "Mèo NÓNG và tự CHẠY, chạm vào là chết. Lúc đầu NƯỚC KHÔNG CHÌM nên mèo chạy cả trên nước. Rút chữ KHÔNG ra đúng lúc mèo đang ở trên nước: nước lại CHÌM, mèo chìm theo. Muốn lội qua nước vào cổng thì sau đó phải đưa KHÔNG về chỗ cũ.",
    map: ["....~......", ".w.~.....~.", "...~w~~~...", "wN........w", "m-..w~~c~wg", ".4..w~..~~.", "W=3M=1G=6..", "N=4C=5C=^.."],
    fixed: [[1, 3], [1, 5], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6], [0, 7], [1, 7], [2, 7], [3, 7], [4, 7], [5, 7], [6, 7], [7, 7], [8, 7]],
  },
  {
    han: "降落", name: "Hạ cánh", paper: "pink", key: 2, sk: true,
    riddle: "Bay qua lửa thì dễ, đáp xuống đúng chỗ mới khó.",
    hint: "Mèo ghép CHUỘT LÀ BAY: chuột bay qua lửa mà không cháy (thứ BAY chỉ chạm thứ cũng BAY). Nhưng cổng không bay nên chuột bay thì không vào được cổng. Đưa chuột tới cổng đúng lúc mèo đẩy chữ ra khỏi câu, chuột hạ xuống ngay trên cổng.",
    map: ["..f..wfM..w", "w.mw.w..9.w", ".f..ww.=..w", "f.wf.w..f.w", "gw...w..fcw", "wwwwwwwwwww", "W=3F=5G=6..", "M&C=1......"],
    fixed: [[0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6], [0, 7], [1, 7], [2, 7], [3, 7], [4, 7]],
  },
  {
    han: "群鼠", name: "Bầy chuột", paper: "sage", key: -2, sk: true,
    riddle: "Một mình thì không làm nổi, mà đá thì biết đâu lại thành bạn.",
    hint: "Ghép ĐÁ LÀ CHUỘT: mọi hòn đá hoá chuột, cả bầy cùng đi theo một phím, con nào vướng thì đứng lại. Đá nằm trên lửa hoá chuột là cháy ngay. Dùng cả bầy để đẩy THẮNG vào CỔNG LÀ và đưa một con vào cổng.",
    map: [".m.....w.", "......f=.", "wwfG=.MR.", "....r.w.r", ".wwfwf.6.", "g....r...", "W=3M=1F=5"],
    fixed: [[3, 2], [4, 2], [6, 2], [0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6]],
  },
  {
    han: "字渡", name: "Chữ bay qua sông", paper: "blue", key: -3, sk: true,
    riddle: "Chuột bay được nhưng không đáp được, chữ đáp được nhưng không bay qua sông.",
    hint: "CHUỘT LÀ BAY bị ghim, chuột bay thì không vào được cổng. Bên kia sông có CHUỘT KHÔNG còn thiếu chữ BAY, nhưng chữ thả xuống sông là chìm. Ghép CHỮ LÀ BAY rồi đẩy cả câu qua sông (chữ bay thì không chìm), sang bờ bên kia mới đẩy BAY vào chỗ trống, đứng trên bờ chứ đừng đứng trên nước.",
    map: ["wwwwwwwwwwww", "wwmwww~~~M.w", "w..w..~~~-.w", "w.T...~~~..w", "ww.=9.~~~..w", "w...w.~~~.gw", "wwwwwwwwwwww", "W=3M=1M=9...", "N=4G=6......"],
    fixed: [[9, 1], [9, 2], [0, 7], [1, 7], [2, 7], [3, 7], [4, 7], [5, 7], [6, 7], [7, 7], [8, 7], [0, 8], [1, 8], [2, 8], [3, 8], [4, 8], [5, 8]],
  },
];
// the bought hint (owner): just the chain of rules to make, map by map
const C2_CHAIN = [
  "Ghép CỔNG LÀ THẮNG → đưa chuột tới cổng",
  "Phá TƯỜNG LÀ CHẶN → ghép CỔNG LÀ THẮNG",
  "Phá TƯỜNG LÀ CHẶN → ghép TƯỜNG LÀ THẮNG",
  "Ghép CHUỘT LÀ THẮNG",
  "Ghép MÈO LÀ CÁ → ghép CÁ LÀ THẮNG",
  "Ghép CHUM LÀ THẮNG",
  "Ghép CỔNG LÀ THẮNG → ghép LỬA LÀ CHUỘT",
  "Ghép CHUM LÀ THẮNG",
  "Ghép TƯỜNG LÀ ĐẨY → xô tường khỏi cổng",
  "Ghép TƯỜNG LÀ CỔNG → phá TƯỜNG LÀ CỔNG (trả chữ về) → ghép CỔNG LÀ THẮNG",
  "Ghép NƯỚC LÀ ĐẨY → đẩy nước vào lửa",
  "Ghép LỬA LÀ CHUỘT",
  "Ghép CỔNG LÀ THẮNG → thả chữ thừa xuống sông",
  "Ghép CÁ LÀ ĐI",
  "Ghép CHÌA LÀ MỞ → đẩy chìa vào cửa",
  "Phá CHUM LÀ CHẶN → ghép CHUM LÀ YẾU → bước vào chum → đẩy chìa vào cửa",
  "Ghép ĐÁ LÀ KÉO → kéo đá ra khỏi ngõ",
  "Kéo chữ ra khỏi góc → ghép CỔNG LÀ THẮNG",
  "Ghép TƯỜNG KHÔNG CHẶN",
  "Ghép MÈO LÀ CHẠY → mèo tự đẩy chữ THẮNG thành CỔNG LÀ THẮNG",
  "Ghép LỬA LÀ YẾU → đẩy chum vào lửa → cổng hiện ra",
  "Ghép CHÌA CÓ CHÌA → đẩy chìa qua ba cửa",
  "Ghép CHUỘT VÀ CỔNG LÀ BAY → bay qua sông",
  "Ghép CHUỘT LÀ BAY → kéo hai hòn đá xuống sông → phá CHUỘT LÀ BAY",
  "Giữ CHỮ LÀ ĐI → ghép CỔNG LÀ THẮNG → cho một chữ chạm cổng",
  "Ghép CHUỘT LÀ CHUỘT → đẩy chữ CHUỘT qua ngõ",
  "Ghép CỔNG LÀ THẮNG → phá CÁ LÀ ĐI → ghép CHUỘT LÀ ĐI",
  "Ghép CHUM LÀ ĐẨY → đẩy chum xuống sông → phá CHUM LÀ ĐẨY → thả chữ ĐẨY xuống sông",
  "Phá TƯỜNG LÀ CHẶN → ghép RƠM LÀ CÁ",
  "Ghép ĐÁ LÀ ĐẨY → ghép TƯỜNG LÀ NƯỚC",
  "Phá TƯỜNG LÀ CHẶN → ghép CHUM LÀ ĐẨY → phá CHUM LÀ ĐẨY → ghép CỔNG LÀ THẮNG",
  "Ghép MÈO LÀ ĐI → mèo nhảy sông → phá MÈO LÀ ĐI → thả chữ LÀ xuống sông",
  "Ghép NƯỚC LÀ CHUỘT → ghép CỔNG LÀ THẮNG",
  "Ghép CỔNG LÀ RƠM → ghép RƠM LÀ THẮNG",
  "Ghép TƯỜNG LÀ ĐẨY → ghép CỔNG LÀ THẮNG",
  "Đẩy mèo xuống sông → phá NƯỚC LÀ CHÌM → ghép CỔNG LÀ THẮNG",
  "Ghép CHUỘT CÓ CHUỘT → ghép CHUỘT LÀ MỞ → lội qua sông, bước vào cửa",
  "Ghép CHỮ LÀ MỞ → đẩy chữ VÀ vào cửa → phá CHỮ LÀ MỞ → ghép CỔNG LÀ THẮNG",
  "Ghép CHÌA LÀ KÉO → kéo chìa ra khỏi ngách → phá CHÌA LÀ KÉO → ghép CHÌA LÀ ĐẨY → đẩy chìa vào cửa",
  "Ghép CHUM LÀ ĐẨY → ghép ĐÁ LÀ YẾU → phá CHUM LÀ ĐẨY → ghép CHÌA LÀ ĐẨY",
  "Ghép CHUỘT LÀ CHẠY → nhảy qua sông → ghép CỔNG LÀ THẮNG",
  "Ghép NƯỚC CÓ ĐÁ → đẩy đá xuyên sông → phá NƯỚC CÓ ĐÁ → mang chữ CÓ qua sông → ghép CHUM CÓ CỔNG → đẩy chum xuống sông",
  "Ghép CHÌA VÀ CHUỘT LÀ ĐI → dẫn chìa vào cửa",
  "Ghép MÈO CÓ CÁ → ghép MÈO LÀ YẾU",
  "Ghép CỬA LÀ KÉO → dắt cửa ra khỏi ngõ → phá CỬA LÀ KÉO → ghép CỔNG LÀ THẮNG",
  "Ghép CHỮ CÓ CỔNG → phá TƯỜNG LÀ CHẶN → thả chữ LÀ xuống sông",
  "Ghép CỔNG LÀ THẮNG → phá LỬA LÀ NÓNG",
  "Ghép MÈO KHÔNG ĐI → phá MÈO KHÔNG ĐI → ghép CỔNG LÀ THẮNG",
  "Ghép MÈO LÀ CHẠY → ghép CỔNG LÀ THẮNG → phá MÈO LÀ CHẠY",
  "Ghép CHUỘT VÀ MÈO LÀ ĐI → ghép CHỮ LÀ THẮNG",
  "Ghép CỔNG KHÔNG YẾU → ghép CỔNG LÀ THẮNG",
  "Ghép CHUỘT LÀ CHUỘT → ghép CỔNG LÀ THẮNG",
  "Phá NƯỚC KHÔNG CHÌM (lúc mèo ở trên nước) → ghép NƯỚC KHÔNG CHÌM",
  "Ghép CHUỘT LÀ BAY → phá CHUỘT LÀ BAY",
  "Ghép ĐÁ LÀ CHUỘT → ghép CỔNG LÀ THẮNG",
  "Ghép CHỮ LÀ BAY → phá CHỮ LÀ BAY → ghép CHUỘT KHÔNG BAY",
];
const C2_FIRST_HARD = C2LEVELS.findIndex(l => l.hard);
const C2_FIRST_BH = C2LEVELS.findIndex(l => l.bh);   // Biến hoá: the Baba-style words (owner)
const C2_FIRST_SK = C2LEVELS.findIndex(l => l.sk);   // Siêu khó: 30 hard maps, open after the last Biến hoá map
